spring:
  datasource:
    url: jdbc:mysql://mysql-myapp-gzh-dev.mysql.database.azure.com:3306/db?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true
    username: zhihaoguo@microsoft.com@mysql-myapp-gzh-dev
    azure:
      passwordlessEnabled: true

  #
  sql:
    init:
      mode: always